/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    'navigation-links': NavigationLink;
    redirects: Redirect;
    headers: Header;
    footers: Footer;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    'navigation-links': NavigationLinksSelect<false> | NavigationLinksSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    headers: HeadersSelect<false> | HeadersSelect<true>;
    footers: FootersSelect<false> | FootersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'page-settings': PageSetting;
    'site-settings': SiteSetting;
    'theme-settings': ThemeSetting;
    'seo-settings': SeoSetting;
  };
  globalsSelect: {
    'page-settings': PageSettingsSelect<false> | PageSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'theme-settings': ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
    'seo-settings': SeoSettingsSelect<false> | SeoSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Flexible website pages with reusable layout blocks, SEO controls, and publishing settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Compose the page with reusable frontend sections.
   */
  layout?: Hero36Block[] | null;
  metaTitle: string;
  metaDescription: string;
  /**
   * Resolved from the current saved slug and parent hierarchy.
   */
  publicUrlPreview?: string | null;
  /**
   * Use this for nested page hierarchies like /services/web-development.
   */
  parent?: (number | null) | Page;
  /**
   * Create or maintain a reusable link record for this page.
   */
  showInNavigation?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero36Block".
 */
export interface Hero36Block {
  badge?: {
    text?: string | null;
  };
  heading: string;
  description?: string | null;
  cards: {
    title: string;
    description: string;
    href?: string | null;
    visualType: 'icon' | 'image';
    icon?: ('blocks' | 'database' | 'layout' | 'rocket') | null;
    image?: (number | null) | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero36';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Reusable destinations for menus, CTAs, legal links, and utility links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-links".
 */
export interface NavigationLink {
  id: number;
  title: string;
  description?: string | null;
  linkType: 'page' | 'custom';
  page?: (number | null) | Page;
  url?: string | null;
  openInNewTab?: boolean | null;
  /**
   * Shows whether this reusable link is manually managed or synced from a page.
   */
  sourceType: 'manual' | 'pageSynced';
  /**
   * The page that currently owns this synced reusable link.
   */
  syncPage?: (number | null) | Page;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Map old URLs to new destinations during migrations and ongoing URL changes. Some redirects may be auto-generated when a published page URL changes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * The old incoming path to redirect, for example /old-page or /services/web-design.html.
   */
  fromPath: string;
  destinationType: 'page' | 'custom';
  page?: (number | null) | Page;
  url?: string | null;
  /**
   * Use 301 for permanent site migrations. Use 302 only for temporary routing changes.
   */
  statusCode: '301' | '302';
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reusable site header presets powered by header layout blocks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headers".
 */
export interface Header {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Select the header block variant to use for this preset.
   */
  layout: HeaderNavbar12Block[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderNavbar12Block".
 */
export interface HeaderNavbar12Block {
  logoMode: 'siteSettingsLogo' | 'customLogo';
  customLogo?: (number | null) | Media;
  /**
   * Configure the main navigation structure for this header.
   */
  navigationItems?:
    | {
        /**
         * Optional top-level label override. Leave blank to use the reusable link title.
         */
        label?: string | null;
        /**
         * Optional top-level destination. If children are added, this becomes the overview link.
         */
        link?: (number | null) | NavigationLink;
        children?:
          | {
              /**
               * Optional label override. Leave blank to use the reusable link title.
               */
              label?: string | null;
              /**
               * Optional description for dropdown items.
               */
              description?: string | null;
              link: number | NavigationLink;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional reusable links shown to the right of the navigation.
   */
  secondaryActions?:
    | {
        /**
         * Optional label override. Leave blank to use the reusable link title.
         */
        label?: string | null;
        link: number | NavigationLink;
        id?: string | null;
      }[]
    | null;
  cta?: {
    enabled?: boolean | null;
    /**
     * Optional button label override. Leave blank to use the reusable link title.
     */
    label?: string | null;
    link?: (number | null) | NavigationLink;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'headerNavbar12';
}
/**
 * Reusable site footer presets powered by footer layout blocks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footers".
 */
export interface Footer {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Select the footer block variant to use for this preset.
   */
  layout: Footer2Block[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Footer2Block".
 */
export interface Footer2Block {
  logoMode: 'siteSettingsLogo' | 'customLogo';
  customLogo?: (number | null) | Media;
  description?: string | null;
  /**
   * Configure the footer sections for this footer layout.
   */
  sections?:
    | {
        title: string;
        links?:
          | {
              /**
               * Optional label override. Leave blank to use the reusable link title.
               */
              name?: string | null;
              link: number | NavigationLink;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  legalLinks?:
    | {
        /**
         * Optional label override. Leave blank to use the reusable link title.
         */
        name?: string | null;
        link: number | NavigationLink;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'footer2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'navigation-links';
        value: number | NavigationLink;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'headers';
        value: number | Header;
      } | null)
    | ({
        relationTo: 'footers';
        value: number | Footer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero36?: T | Hero36BlockSelect<T>;
      };
  metaTitle?: T;
  metaDescription?: T;
  publicUrlPreview?: T;
  parent?: T;
  showInNavigation?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero36Block_select".
 */
export interface Hero36BlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        text?: T;
      };
  heading?: T;
  description?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        visualType?: T;
        icon?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-links_select".
 */
export interface NavigationLinksSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  linkType?: T;
  page?: T;
  url?: T;
  openInNewTab?: T;
  sourceType?: T;
  syncPage?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  destinationType?: T;
  page?: T;
  url?: T;
  statusCode?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headers_select".
 */
export interface HeadersSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  layout?:
    | T
    | {
        headerNavbar12?: T | HeaderNavbar12BlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderNavbar12Block_select".
 */
export interface HeaderNavbar12BlockSelect<T extends boolean = true> {
  logoMode?: T;
  customLogo?: T;
  navigationItems?:
    | T
    | {
        label?: T;
        link?: T;
        children?:
          | T
          | {
              label?: T;
              description?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  secondaryActions?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        enabled?: T;
        label?: T;
        link?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footers_select".
 */
export interface FootersSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  layout?:
    | T
    | {
        footer2?: T | Footer2BlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Footer2Block_select".
 */
export interface Footer2BlockSelect<T extends boolean = true> {
  logoMode?: T;
  customLogo?: T;
  description?: T;
  sections?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              name?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  legalLinks?:
    | T
    | {
        name?: T;
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-settings".
 */
export interface PageSetting {
  id: number;
  /**
   * Choose which published page should render at the root URL (/).
   */
  homepage?: (number | null) | Page;
  /**
   * Choose which saved header preset should render site-wide.
   */
  activeHeader?: (number | null) | Header;
  /**
   * Choose which saved footer preset should render site-wide.
   */
  activeFooter?: (number | null) | Footer;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  googleMapEmbedUrl?: string | null;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Control the frontend theme preset and light or dark mode behavior.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: number;
  /**
   * Select which frontend theme preset is loaded for the site.
   */
  themeColor: 'default' | 'blue' | 'sera';
  /**
   * Choose whether the site follows the system preference or forces light/dark mode.
   */
  colorScheme: 'system' | 'light' | 'dark';
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Default SEO values used when a page does not provide its own overrides.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings".
 */
export interface SeoSetting {
  id: number;
  defaultTitle?: string | null;
  /**
   * Example: %s | Your Site Name
   */
  titleTemplate?: string | null;
  defaultDescription?: string | null;
  defaultImage?: (number | null) | Media;
  robots?: ('index,follow' | 'noindex,follow' | 'index,nofollow' | 'noindex,nofollow') | null;
  googleSiteVerification?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-settings_select".
 */
export interface PageSettingsSelect<T extends boolean = true> {
  homepage?: T;
  activeHeader?: T;
  activeFooter?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  favicon?: T;
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  googleMapEmbedUrl?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        youtube?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  themeColor?: T;
  colorScheme?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  defaultTitle?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  defaultImage?: T;
  robots?: T;
  googleSiteVerification?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}